### ISSUE TITLE
actually this plugin doesnt allow for different raklib versions to join so only 1.16.X can join ur server with this plugin

### ISSUE THREAD

**Issue by Jviguy** [BajanVlogs/MultiProtocol#4]

**Comment by ghost** [comment]
who asked @Jviguy ?

**Comment by Jviguy** [comment]
Bro this is from like a year ago go get a life God damn.

**Comment by Jviguy** [comment]
This is from a year ago go get a life.

**Comment by Khuirul-Huda** [comment]
why not close this issue? @Jviguy

**Comment by Jviguy** [comment]
Because I have a life and don't care to go close an issue from a year ago?

**Comment by Khuirul-Huda** [comment]
you have a life? then don't reply to this issue, This will just be a waste
of time, just close the issue

Pada tanggal Jum, 11 Feb 2022 19.13, Jviguy ***@***.***>
menulis:

**Comment by Jviguy** [comment]
Only reason I replied is because peppa's a friend, idk who tf u are, but I'm gonna leave it open just in spite gn.
