### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by ghost** [BajanVlogs/MultiProtocol#6]
not working bro 1.20+

**Comment by ItsToxicGG** [comment]
Well it shouldnt actually work no matter what, the plugin basically wont work, alot of people tried previously the same method this guy is using but it will never work, multiversion/protocol plugins are way advance to work not like this, this just attempts to make pocketmine think that protocol version is the latest protocol version which shouldnt work.

**Comment by ghost** [comment]
> Well it shouldnt actually work no matter what, the plugin basically wont work, alot of people tried previously the same method this guy is using but it will never work, multiversion/protocol plugins are way advance to work not like this, this just attempts to make pocketmine think that protocol version is the latest protocol version which shouldnt work.

@ItsToxicGG Thanks for sharing that. However, it seems like the plugin might have some technical limitations hindering its functionality. Are there any other alternatives that might better achieve the same goal?

**Comment by ItsToxicGG** [comment]
well a better solution is probably using an custom pocketmine-mp, the best out right now is NetherGamesMC's, but as far as i know theres no other plugin right now that supports pm 5 and has functional/working multiversion.

**Comment by OfficialLilKev** [comment]
try it out now and let me know what it says or does

**Comment by OfficialLilKev** [comment]
> Well it shouldnt actually work no matter what, the plugin basically wont work, alot of people tried previously the same method this guy is using but it will never work, multiversion/protocol plugins are way advance to work not like this, this just attempts to make pocketmine think that protocol version is the latest protocol version which shouldnt work.

this used to work just fine back on PMMP 4 but everything got changed around so imma try and tweak it and see what I can get working

**Comment by OfficialLilKev** [comment]
issue has been fixed
